{% set name = "planet" %}
{% set version = "2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planet-{{ version }}.tar.gz
  sha256: 16205aa92959f80816a58bfcf1b21e1184dec52e5e3040c2f2242bbe5149e08f

build:
  noarch: python
  entry_points:
    - planet = planet.cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8.0
    - geojson
    - httpx >=0.23.0
    - jsonschema
    - pyjwt >=2.1
    - tqdm >=4.56
    - typing-extensions
test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - pl-gideon
    - ocefpaf
