{% set name = "planet" %}
{% set version = "2.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/planet-{{ version }}.tar.gz
  sha256: 1bc008e1c10db31d01ebb73f3c134a3558411d2dbd071102a97a00b42ff8176f

build:
  entry_points:
    - planet=planet.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - click >=8.0,!=8.2.1
    - geojson
    - httpx >=0.28.0
    - jsonschema
    - pyjwt >=2.1
    - tqdm >=4.56
    - typing-extensions
test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - pl-gideon
    - ocefpaf
