{% set version = "1.2.1" %}

package:
  name: planet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/planet/planet-{{ version }}.tar.gz
  sha256: fb989a00d2051327893b491953d3db4d9945e2ba1b2c6642dcbcbd0c173f1185

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - planet=planet.scripts:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - click
    - requests
    - requests-futures

test:
  imports:
    - planet
    - planet.api
    - planet.scripts
  commands:
    - planet --help

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Planet API Client'

extra:
  recipe-maintainers:
    - ocefpaf
