{% set name = "planet" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/planet-{{ version }}.tar.gz
  sha256: 4a23713cd6cfa9c5cf2937df98a651873b2047bcd9a5c0559e486f3a58fb353d

build:
  entry_points:
    - planet=planet.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - click >=8.0
    - geojson
    - httpx >=0.28.0
    - jsonschema
    - pyjwt >=2.1
    - tqdm >=4.56
    - typing-extensions
test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - pl-gideon
    - ocefpaf
