{% set name = "planet" %}
{% set version = "2.0.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planet-{{ version }}.tar.gz
  sha256: 2d229f60af473a17e25a19f3fefc2d2abf9fc50b74d3b892b0e444e150b3fa22

build:
  noarch: python
  entry_points:
    - planet = planet.cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8.0
    - geojson
    - httpx ==0.23.0
    - jsonschema
    - pyjwt >=2.1
    - tqdm >=4.56
test:
  imports:
    - planet
  commands:
    - pip check
    - planet --help
  requires:
    - pip

about:
  home: https://github.com/planetlabs/planet-client-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Planet API Client

extra:
  recipe-maintainers:
    - ocefpaf
    - sgillies
